// gen-ts-types crawls internal/transit/api/*.go and generates TypeScript
// interfaces from Go structs with json tags.
//
// Usage: go run ./cmd/gentstypes
//
// Output: web/transit/api.gen.ts
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const (
	apiPkg  = "internal/transit/api"
	outFile = "web/transit/api.gen.ts"
)

type fieldInfo struct {
	jsonName string
	tsType   string
	optional bool
}

type structInfo struct {
	name    string
	doc     string
	fields  []fieldInfo
	srcFile string
}

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, apiPkg, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	var structs []structInfo

	for _, pkg := range pkgs {
		for filename, file := range pkg.Files {
			base := filepath.Base(filename)
			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}

				// Only exported types
				if !ts.Name.IsExported() {
					return true
				}

				si := structInfo{
					name:    ts.Name.Name,
					srcFile: base,
				}

				// Grab doc comment
				if ts.Doc != nil {
					si.doc = strings.TrimSpace(ts.Doc.Text())
				}

				for _, f := range st.Fields.List {
					if f.Tag == nil {
						continue
					}
					tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`"))
					jsonTag := tag.Get("json")
					if jsonTag == "" || jsonTag == "-" {
						continue
					}

					parts := strings.Split(jsonTag, ",")
					jsonName := parts[0]
					tsType := goTypeToTS(f.Type)

					// Only pointer types are truly optional/nullable.
					// omitempty on value types (string, int, bool) just omits
					// zero values in JSON but the frontend treats them as present.
					_, isPtr := f.Type.(*ast.StarExpr)

					fi := fieldInfo{
						jsonName: jsonName,
						tsType:   tsType,
						optional: isPtr,
					}
					si.fields = append(si.fields, fi)
				}

				structs = append(structs, si)
				return true
			})
		}
	}

	// Sort by name for stable output
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].name < structs[j].name
	})

	var b strings.Builder

	b.WriteString("// ===========================================================================\n")
	b.WriteString("// DO NOT EDIT — generated by: go run scripts/gen-ts-types.go\n")
	b.WriteString("// Source: internal/transit/api/*.go\n")
	b.WriteString("// ===========================================================================\n\n")

	for i, s := range structs {
		if i > 0 {
			b.WriteString("\n")
		}
		if s.doc != "" {
			b.WriteString("/** " + s.doc + " */\n")
		}
		b.WriteString("export interface " + s.name + " {\n")
		for _, f := range s.fields {
			opt := ""
			if f.optional {
				opt = "?"
			}
			b.WriteString("  " + f.jsonName + opt + ": " + f.tsType + ";\n")
		}
		b.WriteString("}\n")
	}

	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir error: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outFile, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d interfaces to %s\n", len(structs), outFile)
}

func goTypeToTS(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			return "number"
		case "bool":
			return "boolean"
		default:
			// Another struct in the same package
			return t.Name
		}
	case *ast.StarExpr:
		// *T → T | null
		inner := goTypeToTS(t.X)
		return inner + " | null"
	case *ast.ArrayType:
		elem := goTypeToTS(t.Elt)
		// Fixed-size arrays like [2]float64 → [number, number]
		if t.Len != nil {
			if lit, ok := t.Len.(*ast.BasicLit); ok && lit.Value == "2" {
				return "[" + elem + ", " + elem + "]"
			}
		}
		return elem + "[]"
	case *ast.MapType:
		key := goTypeToTS(t.Key)
		val := goTypeToTS(t.Value)
		return "Record<" + key + ", " + val + ">"
	case *ast.SelectorExpr:
		// time.Time → string (RFC3339)
		if ident, ok := t.X.(*ast.Ident); ok && ident.Name == "time" && t.Sel.Name == "Time" {
			return "string"
		}
		return "unknown"
	default:
		return "unknown"
	}
}
