// ===========================================================================
// DO NOT EDIT — generated by: go run scripts/gen-ts-types.go
// Source: internal/transit/api/*.go
// ===========================================================================

export interface CancelledTrip {
  trip_id: string;
  route_id: string;
  start_time: string;
  end_time: string;
  headsign: string;
  upcoming: boolean;
  lead_min: number;
  lead_label: string;
}

export interface Itinerary {
  departure: string;
  arrival: string;
  duration_min: number;
  transfers: number;
  leave_by: string;
  label: string;
  next_departures: string[];
  legs: Leg[];
  cancelled: boolean;
  cancelled_saved_min: number;
}

export interface KpiItem {
  key: string;
  value: string;
}

export interface KpisResponse {
  has_data: boolean;
  kpis: KpiItem[];
}

export interface Leg {
  type: string;
  route_id: string;
  route_name: string;
  route_color: string;
  headsign: string;
  from: LegStop;
  to: LegStop;
  departure: string;
  arrival: string;
  duration_min: number;
  distance_m: number;
  stops: number;
  hint: string;
}

export interface LegStop {
  stop_id: string;
  name: string;
  lat: number;
  lon: number;
  dest_distance_m: number;
  dest_walk_min: number;
}

export interface PlanResponse {
  itineraries: Itinerary[];
}

export interface PredictionsResponse {
  predictions: StopPrediction[];
  updated_at?: string | null;
}

export interface RouteShape {
  route_id: string;
  coordinates: [number, number][];
}

export interface Stop {
  stop_id: string;
  stop_name: string;
  lat: number;
  lon: number;
  routes: number;
  route_ids: string[];
  transfer: boolean;
  is_terminal: boolean;
}

export interface StopAlert {
  header: string;
  description: string;
}

export interface StopPrediction {
  route_id: string;
  route_name: string;
  headsign: string;
  scheduled: string;
  predicted: string;
  delay_seconds?: number | null;
  minutes_away: number;
  status: string;
  route_color: string;
}

export interface Timepoint {
  stop_id: string;
  routes: string[];
  colors: string[];
}

export interface Vehicle {
  id: string;
  route_id: string;
  lat: number;
  lon: number;
  bearing: number;
  speed: number;
  status: string;
  stop_id: string;
  near_stop: string;
  delay?: number | null;
}

export interface VehiclePayload {
  timestamp: number;
  vehicles: Vehicle[];
  stop_served: Record<string, number>;
}
